services:
  # O Coração: Mensageria Ultra-rápida
  redis:
    image: redis:alpine
    container_name: dungeon_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # A Persistência: Rankings e Histórico
  postgres:
    image: postgres:15-alpine
    container_name: dungeon_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tcc_password
      POSTGRES_DB: dungeon_master
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro # Cria as tabelas automaticamente
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dungeon_master"]
      interval: 5s
      timeout: 3s
      retries: 5

  # O Porteiro: Gerencia as conexões dos 90 alunos
  node-gateway:
    build: 
      context: ./gateway-node
      dockerfile: Dockerfile
    container_name: node_gateway
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy

  # Engine de Batalha (Go)
  go-engine:
    build: 
      context: ./go-engine
      dockerfile: Dockerfile
    container_name: go_engine
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6379
      - DATABASE_URL=postgres://admin:tcc_password@postgres:5432/dungeon_master?sslmode=disable
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy # Garante que as tabelas existam antes de ligar a engine

  # Observabilidade: Coleta de métricas em tempo real
  prometheus:
    image: prom/prometheus
    container_name: dungeon_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      node-gateway:
        condition: service_started
      go-engine:
        condition: service_started

  # Painel de Controle: Dashboard do Show
  grafana:
    image: grafana/grafana
    container_name: dungeon_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true 
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pgdata:
  grafanadata: