version: '3.8'

services:
  # O Coração: Mensageria Ultra-rápida
  redis:
    image: redis:alpine
    container_name: dungeon_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # A Persistência: Rankings e Histórico (Persistente)
  postgres:
    image: postgres:15-alpine
    container_name: dungeon_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tcc_password
      POSTGRES_DB: dungeon_master
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dungeon_master"]
      interval: 5s
      timeout: 3s
      retries: 5

  # O Porteiro: Gerencia as conexões dos 90 alunos
  node-gateway:
    build: ./gateway-node
    container_name: node_gateway
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy

  # Observabilidade: Coleta de métricas em tempo real
  prometheus:
    image: prom/prometheus
    container_name: dungeon_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      redis:
        condition: service_healthy

  # Painel de Controle: Onde você mostra o "show" no telão
  grafana:
    image: grafana/grafana
    container_name: dungeon_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - prometheus
  go-engine:
    build: ./go-engine
    container_name: go_engine
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy    

volumes:
  pgdata:
  grafanadata: