global:
  scrape_interval: 1s     # Coleta dados a cada 1 segundo (Máxima precisão para o TCC)
  evaluation_interval: 1s

scrape_configs:
  # 1. Prometheus se monitorando
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Gateway Node.js (Socket.io)
  - job_name: 'node-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-gateway:3001'] # Nome do serviço no docker-compose

  # 3. Engine de Batalha (Go)
  - job_name: 'go-engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['go-engine:8080'] # Nome do serviço no docker-compose